# Generated by Django 4.1.3 on 2022-12-03 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=50)),
                ('Password', models.CharField(max_length=12)),
                ('IsActive', models.BooleanField(default=False)),
                ('DateCreated', models.DateTimeField(auto_now_add=True)),
                ('DateModified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'master',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(max_length=50)),
                ('ProductPrice', models.DecimalField(decimal_places=2, max_digits=7)),
                ('ProductQuantity', models.IntegerField()),
                ('ProductDescription', models.TextField(max_length=250)),
                ('ProductImage', models.ImageField(upload_to='Products/')),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'productcategory',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=50)),
                ('Lastname', models.CharField(max_length=50)),
                ('Contact', models.CharField(max_length=50)),
                ('ProfileImage', models.ImageField(default='avatar.png', upload_to='profiles/')),
                ('Gender', models.CharField(choices=[('m', 'male'), ('f', 'female'), ('o', 'other')], max_length=10)),
                ('BirthDate', models.DateField(default='1990-01-01')),
                ('State', models.CharField(blank=True, default='', max_length=30)),
                ('City', models.CharField(blank=True, default='', max_length=30)),
                ('Address', models.CharField(blank=True, default='', max_length=30)),
                ('Pincode', models.CharField(blank=True, default='', max_length=6)),
                ('Master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GroceryStore_app.master')),
            ],
            options={
                'db_table': 'userprofile',
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GroceryStore_app.product')),
                ('UserProfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GroceryStore_app.userprofile')),
            ],
            options={
                'db_table': 'wishlist',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='Category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GroceryStore_app.productcategory'),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField()),
                ('TotalPrice', models.DecimalField(decimal_places=2, max_digits=7)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GroceryStore_app.product')),
                ('UserProfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GroceryStore_app.userprofile')),
            ],
            options={
                'db_table': 'cart',
            },
        ),
    ]
