# Generated by Django 4.1.3 on 2022-12-26 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroceryStore_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='Address',
            new_name='HomeAddress',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='OfficeAddress',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='OtherAddress',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
