# Generated by Django 4.1.3 on 2022-12-26 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroceryStore_app', '0002_rename_address_userprofile_homeaddress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='Gender',
            field=models.CharField(max_length=10),
        ),
    ]
